development:
  adapter: postgresql
  encoding: unicode
  port: 5432
  database: solidux_store_dev
  username: postgres
  pool: 5
  password:

production:
  adapter: postgresql
  encoding: unicode
  port: 5432
  database: solidux_store_prod
  username: postgres
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: unicode
  port: 5432
  database: solidux_store_test
  username: postgres
  pool: 5
  password:
